# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10eDB91bMOUsLgV4nwcvh08ySiA6lVGri
"""

import numpy as np
import matplotlib.pyplot as plt

# ---------------------------
# 1) DC Motor parametreleri
# ---------------------------
R = 1.0
L = 0.5
Kt = 0.01
Kb = 0.01
J = 0.01
B = 0.001
Vmax = 24.0

# ---------------------------
# 2) Üyelik fonksiyonları (Ayar 8'deki gibi)
# ---------------------------
def triangular(x, a, b, c):
    x = np.asarray(x)
    mu = np.zeros_like(x, dtype=float)
    left = (a < x) & (x <= b)
    mu[left] = (x[left] - a) / (b - a + 1e-12)
    right = (b < x) & (x < c)
    mu[right] = (c - x[right]) / (c - b + 1e-12)
    mu[x == b] = 1.0
    return mu

# --- Hata (e) için 5 üyelik fonksiyonu ---
max_e = 100.0
e_NB = (-max_e*1.2, -max_e, -max_e*0.6)
e_NS = (-max_e*0.8, -max_e*0.4, 0)
e_Z  = (-max_e*0.1, 0, max_e*0.1)
e_PS = (0, max_e*0.4, max_e*0.8)
e_PB = (max_e*0.6, max_e, max_e*1.2)

# --- Hata değişimi (de/dt) için 3 üyelik fonksiyonu ---
max_de = 400.0
de_N = (-max_de*1.2, -max_de*0.8, -max_de*0.2)
de_Z = (-max_de*0.3, 0, max_de*0.3)
de_P = (max_de*0.2, max_de*0.8, max_de*1.2)

# --- Çıkış (u) üyelikleri (0-Merkezli Sistem) ---
u_NB = (-Vmax*1.2, -Vmax*0.8, -Vmax*0.4)
u_NS = (-Vmax*0.5, -Vmax*0.25, 0)
u_Z  = (-Vmax*0.1, 0, Vmax*0.1)
u_PS = (0, Vmax*0.25, Vmax*0.5)
u_PB = (Vmax*0.4, Vmax*0.8, Vmax*1.2)

# --- 5x3 kural tablosu (e x de) ---
rule_table = [
    ['NB', 'NB', 'NS'],
    ['NB', 'NS', 'Z'],
    ['NS', 'Z', 'PS'],
    ['Z', 'PS', 'PB'],
    ['PS', 'PB', 'PB']
]

# Çıkış MF'lerini sözlüğe ekle
output_mfs = {'NB': u_NB, 'NS': u_NS, 'Z': u_Z, 'PS': u_PS, 'PB': u_PB}

# --- Fuzzification ---
def fuzzify_e_de(e, de_dt):
    mu_e = {
        'NB': triangular([e], *e_NB)[0],
        'NS': triangular([e], *e_NS)[0],
        'Z':  triangular([e], *e_Z)[0],
        'PS': triangular([e], *e_PS)[0],
        'PB': triangular([e], *e_PB)[0],
    }
    mu_de = {'N': triangular([de_dt], *de_N)[0], 'Z': triangular([de_dt], *de_Z)[0], 'P': triangular([de_dt], *de_P)[0]}
    return mu_e, mu_de

# --- Mamdani Defuzzification ---
def mamdani_defuzz(e, de_dt, u_disc=np.linspace(-Vmax, Vmax, 1001)):
    mu_e, mu_de = fuzzify_e_de(e, de_dt)
    aggregated = np.zeros_like(u_disc)

    e_labels = ['NB', 'NS', 'Z', 'PS', 'PB']
    de_labels = ['N', 'Z', 'P']

    for i_e, e_lab in enumerate(e_labels):
        for j_de, de_lab in enumerate(de_labels):
            fire = min(mu_e[e_lab], mu_de[de_lab])
            if fire <= 0: continue

            output_label = rule_table[i_e][j_de]
            a, b, c = output_mfs[output_label]

            mu_out = triangular(u_disc, a, b, c)
            aggregated = np.maximum(aggregated, np.minimum(mu_out, fire))

    num, den = np.sum(u_disc * aggregated), np.sum(aggregated)
    return 0.0 if den == 0 else num/den

# ---------------------------
# 3) DC Motor dinamiği
# ---------------------------
def motor_derivatives(x, u, TL=0.0):
    i, w = x
    di = (-R*i - Kb*w + u)/L
    dw = (-B*w + Kt*i - TL)/J
    return np.array([di, dw])

def rk4_step(x, u, dt, TL=0.0):
    k1 = motor_derivatives(x, u, TL)
    k2 = motor_derivatives(x + 0.5*dt*k1, u, TL)
    k3 = motor_derivatives(x + 0.5*dt*k2, u, TL)
    k4 = motor_derivatives(x + dt*k3, u, TL)
    return x + (dt/6)*(k1 + 2*k2 + 2*k3 + k4)

# ---------------------------
# 4) Kapalı çevrim simülasyonu (Ayar 8 Kazançları)
# ---------------------------
def simulate(ref_func, T=5.0, dt=0.001, x0=None):
    if x0 is None: x = np.array([0.0, 0.0])
    else: x = np.array(x0, dtype=float)
    t = np.arange(0, T+dt, dt)
    N = len(t)
    i_hist, w_hist, u_hist, e_hist, ref_hist = np.zeros(N), np.zeros(N), np.zeros(N), np.zeros(N), np.zeros(N)

    prev_e = ref_func(0.0) - x[1]

    integral_e = 0.0
    Ki = 8.0 # Agresif kazanç
    K_fuzzy = 1.0 # Agresif kazanç

    for k in range(N):
        ref = ref_func(t[k])
        e = ref - x[1]
        de_dt = (e - prev_e) / dt

        u_fuzzy = mamdani_defuzz(e, de_dt)
        integral_e += e * dt
        u_total = (K_fuzzy * u_fuzzy) + (Ki * integral_e)

        u_clipped = np.clip(u_total, -Vmax, Vmax)

        if u_total != u_clipped:
            integral_e -= e * dt

        x = rk4_step(x, u_clipped, dt)
        i_hist[k], w_hist[k], u_hist[k], e_hist[k], ref_hist[k] = x[0], x[1], u_clipped, e, ref
        prev_e = e

    return t, w_hist, u_hist, e_hist, ref_hist

# ---------------------------
# 5) Örnek simülasyon (*** T=6.5 GÜNCELLEMESİ ***)
# ---------------------------
if __name__ == "__main__":
    ref_val = 100.0  # rad/s
    def ref(t):
        return ref_val * (t/0.2) if t < 0.2 else ref_val

    # *** DEĞİŞİKLİK BURADA ***
    t, w, u, e, ref_sig = simulate(ref, T=6.5, dt=0.001) # 10.0 idi, 6.5 oldu

    plt.figure(figsize=(10,6))
    plt.subplot(3,1,1)
    plt.plot(t, ref_sig, '--', label='Ref')
    plt.plot(t, w, label='Omega')
    plt.ylabel('Speed (rad/s)'); plt.legend(); plt.grid(True)
    plt.title('Simulasyon Sonucu (6.5 Saniye)')

    plt.subplot(3,1,2)
    plt.plot(t, u); plt.ylabel('Voltage (V)'); plt.grid(True)
    plt.ylim(-Vmax*0.1, Vmax*1.1)

    plt.subplot(3,1,3)
    plt.plot(t, e); plt.ylabel('Error'); plt.xlabel('Time (s)'); plt.grid(True)

    plt.tight_layout(); plt.show()


    # ============================================================
    # 6) TÜM ÜYELİK FONKSİYONLARININ GRAFİKLERİ
    # ============================================================
    # Bu grafikler değişmediği için kodları tekrar eklemiyorum,
    # ama istersen "_ = plt.show()" satırlarını yorum satırı (#)
    # yaparak sadece ana simülasyonu görebilirsin.

    # a) Hata (e) üyelik fonksiyonları
    e_vals = np.linspace(-120, 120, 800)
    plt.figure(figsize=(8,4))
    plt.plot(e_vals, triangular(e_vals, *e_NB), label='NB')
    plt.plot(e_vals, triangular(e_vals, *e_NS), label='NS')
    plt.plot(e_vals, triangular(e_vals, *e_Z),  label='Z')
    plt.plot(e_vals, triangular(e_vals, *e_PS), label='PS')
    plt.plot(e_vals, triangular(e_vals, *e_PB), label='PB')
    plt.title('Hata (e) Üyelik Fonksiyonları')
    plt.legend(); plt.grid(True); plt.tight_layout()
    # plt.show() # Sadece simülasyonu görmek için kapatabilirsin

    # b) Hata değişimi (de/dt) üyelik fonksiyonları
    de_vals = np.linspace(-480, 480, 600)
    plt.figure(figsize=(8,4))
    plt.plot(de_vals, triangular(de_vals, *de_N), label='N')
    plt.plot(de_vals, triangular(de_vals, *de_Z), label='Z')
    plt.plot(de_vals, triangular(de_vals, *de_P), label='P')
    plt.title('Hata Türevi (de/dt) Üyelik Fonksiyonları')
    plt.legend(); plt.grid(True); plt.tight_layout()
    # plt.show() # Sadece simülasyonu görmek için kapatabilirsin

    # c) Çıkış (u) üyelik fonksiyonları
    u_vals = np.linspace(-Vmax*1.2, Vmax*1.2, 600)
    plt.figure(figsize=(8,4))
    plt.plot(u_vals, triangular(u_vals, *u_NB), label='NB')
    plt.plot(u_vals, triangular(u_vals, *u_NS), label='NS')
    plt.plot(u_vals, triangular(u_vals, *u_Z),  label='Z (0V)')
    plt.plot(u_vals, triangular(u_vals, *u_PS), label='PS')
    plt.plot(u_vals, triangular(u_vals, *u_PB), label='PB')
    plt.title('Çıkış (u) Üyelik Fonksiyonları (0-Merkezli)')
    plt.xlabel('Düzeltme Gerilimi (u)')
    plt.ylabel('Üyelik Derecesi')
    plt.legend(); plt.grid(True)
    plt.tight_layout()
    # plt.show() # Sadece simülasyonu görmek için kapatabilirsin